export const DEFAULT_MAX_RESULTS = 120;
export const DEFAULT_LIST_PAGE_SIZE = 20;
export const RUN_DETAIL_POLL_INTERVAL_MS = 3_000;
export const APPROVAL_WAITPOINT_TIMEOUT = "24h";
export const APPROVAL_IDEMPOTENCY_KEY_TTL = "25h";
export const DEFAULT_ENRICH_BATCH_SIZE = 25;
export const DEFAULT_ENRICH_REUSE_DAYS = 30;
